GET http://localhost:3000

###

POST http://localhost:3000
Content-Type: application/json
Accept: application/json

{
  "todo": "Belajar NodeJS"
}

###

PUT http://localhost:3000
Content-Type: application/json
Accept: application/json

{
  "ad" : 0,
  "todo": "Programmer zaman now"
}

###
DELETE http://localhost:3000
Content-Type: application/json
Accept: application/json

{
  "id":0
  }